export const profession_data = [
    {
      "Number": 2,
      "Name": "会计师",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "会计，法律，图书馆，聆听，说服，侦查，任意其他两项个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 3,
      "Name": "杂技演员",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "攀爬，闪避，跳跃，投掷，侦查，游泳，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 4,
      "Name": "演员-戏剧演员",
      "Credit": "9-40",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演），乔装，格斗，历史，两项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 5,
      "Name": "演员-电影演员",
      "Credit": "20-90",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演），乔装，汽车驾驶，两项社交技能（取悦、话术、恐吓、说服），心理学，任意两项其他个人或时代特长（如骑乘或格斗）。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 6,
      "Name": "事务所侦探、保安",
      "Credit": "20-45",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "一项社交技能（取悦、话术、恐吓、说服），格斗（斗殴），射击，法律，图书馆，心理学，潜行，追踪。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 7,
      "Name": "精神病医生（古典）",
      "Credit": "10-60",
      "Profession_Point": "教育×4",
      "Skills": "法律，聆听，医学，外语，精神分析，心理学，科学（生物学，化学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 8,
      "Name": "动物训练师",
      "Credit": "10-40",
      "Profession_Point": "教育×2＋外貌或意志×2",
      "Skills": "跳跃，聆听，自然，心理学，科学（动物学），潜行，追踪，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": 2,
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 9,
      "Name": "文物学家（原作向）",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "估价，技艺（任一），历史，图书馆，外语，一项社交技能（取悦、话术、恐吓、说服），侦查，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 10,
      "Name": "古董商",
      "Credit": "30-50",
      "Profession_Point": "教育×4",
      "Skills": "会计，估价，汽车驾驶，两项社交技能（取悦、话术、恐吓、说服），历史，图书馆，导航。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 11,
      "Name": "考古学家（原作向）",
      "Credit": "10-40",
      "Profession_Point": "教育×4",
      "Skills": "估价，考古，历史，外语，图书馆，侦查，机械维修，导航或科学（任一：如化学、物理、地理等）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 12,
      "Name": "建筑师",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "会计，技艺（技术制图），法律，母语，计算机或图书馆，说服，心理学，科学（数学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 13,
      "Name": "艺术家",
      "Credit": "9-50",
      "Profession_Point": "教育×2＋敏捷或意志×2",
      "Skills": "技艺（任一），历史或自然，一项社交技能（取悦、话术、恐吓、说服），外语，心理学，侦查，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": 2,
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 14,
      "Name": "精神病院看护",
      "Credit": "8-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "闪避，格斗（斗殴），急救，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，潜行。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 15,
      "Name": "运动员",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，跳跃，格斗（斗殴），骑乘，一项社交技能（取悦、话术、恐吓、说服），游泳，投掷，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 16,
      "Name": "作家（原作向）",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "技艺（文学），历史，图书馆，自然或神秘学，外语，母语，心理学，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 17,
      "Name": "酒保",
      "Credit": "8-25",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），格斗（斗殴），聆听，心理学，侦查，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 18,
      "Name": "猎人",
      "Credit": "20-50",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "射击，聆听或侦查，自然，导航，外语或生存（任一），科学（生物学或植物学），潜行，追踪。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 19,
      "Name": "书商",
      "Credit": "20-40",
      "Profession_Point": "教育×4",
      "Skills": "会计，估价，汽车驾驶，历史，图书馆，母语，外语，一项社交技能（取悦、话术、恐吓、说服）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 20,
      "Name": "赏金猎人",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "汽车驾驶，电子学或电气维修，格斗或射击，一项社交技能（取悦、话术、恐吓、说服），法律，心理学，追踪，潜行。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 21,
      "Name": "拳击手、摔跤手",
      "Credit": "9-60",
      "Profession_Point": "教育×2＋力量×2",
      "Skills": "闪避，格斗（斗殴），恐吓，跳跃，心理学，侦查，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": 2,
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 22,
      "Name": "管家、男仆、女仆",
      "Credit": "9-40",
      "Profession_Point": "教育×4",
      "Skills": "会计或估价，技艺（任一：如烹饪、裁缝、理发），急救，聆听，外语，心理学，侦查，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 23,
      "Name": "神职人员",
      "Credit": "9-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，历史，图书馆，聆听，外语，一项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 24,
      "Name": "程序员、电子工程师（现代）",
      "Credit": "10-70",
      "Profession_Point": "教育×4",
      "Skills": "计算机，电气维修，电子学、图书馆，科学（数学），侦查，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 25,
      "Name": "黑客/骇客（现代）",
      "Credit": "10-70",
      "Profession_Point": "教育×4",
      "Skills": "计算机，电气维修，电子学，图书馆，侦查，一项社交技能（取悦、话术、恐吓、说服），任意两项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 26,
      "Name": "牛仔",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "闪避，格斗或射击，急救或自然，跳跃，骑乘，生存（任一），投掷，追踪。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 27,
      "Name": "工匠",
      "Credit": "10-40",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "会计，技艺（任二），机械维修，自然，侦查，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 28,
      "Name": "罪犯-刺客",
      "Credit": "30-60",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "乔装，电气维修，格斗，射击，锁匠，机械维修，潜行，心理学。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 29,
      "Name": "罪犯-银行劫匪",
      "Credit": "5-75",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "汽车驾驶，电气维修或机械维修，格斗，射击，恐吓，锁匠，操作重型机械，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 30,
      "Name": "罪犯-打手、暴徒",
      "Credit": "5-30",
      "Profession_Point": "教育×2＋力量×2",
      "Skills": "汽车驾驶，格斗，射击，两项社交技能（取悦、话术、恐吓、说服），心理学，潜行，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": 2,
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 31,
      "Name": "罪犯-窃贼",
      "Credit": "5-40",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "估价，攀爬，电气维修或机械维修，聆听，锁匠，妙手，潜行，侦查。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 32,
      "Name": "罪犯-欺诈师",
      "Credit": "10-65",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "估价，技艺（表演），法律或外语，聆听，两项社交技能（取悦、话术、恐吓、说服），心理学，妙手。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 33,
      "Name": "罪犯-独行罪犯",
      "Credit": "5-65",
      "Profession_Point": "教育×2＋敏捷或外貌×2",
      "Skills": "技艺（表演）或乔装，估价，一项社交技能（取悦、话术、恐吓、说服），格斗或射击，锁匠或机械维修，潜行，心理学，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 34,
      "Name": "罪犯-女飞贼（古典）",
      "Credit": "10-80",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（任意），两项社交技能（取悦、话术、恐吓、说服），格斗（斗殴）或射击（手枪），汽车驾驶，聆听，潜行，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 35,
      "Name": "罪犯-赃物贩子",
      "Credit": "20-40",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "会计，估价，技艺（伪造），历史，一项社交技能（取悦、话术、恐吓、说服），图书馆，侦查，任意一项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 36,
      "Name": "罪犯-赝造者",
      "Credit": "20-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，估价，技艺（伪造），历史，图书馆，侦查，妙手，任意一项其他个人或时代特长（如计算机）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 37,
      "Name": "罪犯-走私者",
      "Credit": "20-60",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "射击，聆听，导航，一项社交技能（取悦、话术、恐吓、说服），汽车驾驶或驾驶（飞行器或船），心理学，妙手，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 38,
      "Name": "罪犯-混混",
      "Credit": "3-10",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，一项社交技能（取悦、话术、恐吓、说服），格斗，射击，跳跃，妙手，潜行，投掷。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 39,
      "Name": "教团首领",
      "Credit": "30-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），神秘学，心理学，侦查，任意其他两项其他个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 40,
      "Name": "除魅师（现代）",
      "Credit": "20-50",
      "Profession_Point": "教育×4",
      "Skills": "两项社交技能（取悦、话术、恐吓、说服），汽车驾驶，格斗（斗殴）或射击，历史，神秘学，心理学，潜行。※经KP允许 可用催眠替换其中一项。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 41,
      "Name": "设计师",
      "Credit": "20-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，技艺（摄影），技艺（任一），计算机或图书馆，机械维修，心理学，侦查，任意一项其他个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 42,
      "Name": "业余艺术爱好者（原作向）",
      "Credit": "50-99",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（任一），射击，外语，骑乘，一项社交技能（取悦、话术、恐吓、说服），任意三项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 43,
      "Name": "潜水员",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "潜水，急救，机械维修，驾驶（船），科学（生物），侦查，游泳，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 44,
      "Name": "医生（原作向）",
      "Credit": "30-80",
      "Profession_Point": "教育×4",
      "Skills": "急救、医学、外语（拉丁文）、心理学、科学（生物学，制药），任两种其他学术或个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 45,
      "Name": "流浪者",
      "Credit": "0-5",
      "Profession_Point": "教育×2＋外貌或敏捷或力量×2",
      "Skills": "攀爬，跳跃，聆听，导航，一项社交技能（取悦、话术、恐吓、说服），潜行，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 46,
      "Name": "司机-私人司机",
      "Credit": "10-40",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "汽车驾驶，两项社交技能（取悦、话术、恐吓、说服），聆听，机械维修，导航，侦查，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 47,
      "Name": "司机-司机",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "会计，汽车驾驶，聆听，一项社交技能（取悦、话术、恐吓、说服），机械维修，导航，心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 48,
      "Name": "司机-出租车司机",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "会计，汽车驾驶，电气维修，话术，机械维修，导航，侦查，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 49,
      "Name": "编辑",
      "Credit": "10-30",
      "Profession_Point": "教育×4",
      "Skills": "会计，历史，母语，两项社交技能（取悦、话术、恐吓、说服），心理学，侦查，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 50,
      "Name": "政府官员",
      "Credit": "50-90",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "取悦，历史，恐吓，话术，聆听，母语，说服，心理学。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 51,
      "Name": "工程师",
      "Credit": "30-60",
      "Profession_Point": "教育×4",
      "Skills": "技艺（技术制图），电气维修，图书馆，机械维修，操作重型机械，科学（工程学，物理），任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 52,
      "Name": "艺人",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演类，如表演、演唱、喜剧等），乔装，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 53,
      "Name": "探险家（古典）",
      "Credit": "55-80",
      "Profession_Point": "教育×2＋外貌或敏捷或力量×2",
      "Skills": "攀爬或游泳，射击，历史，跳跃，自然，导航，外语，生存。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": 2,
      "EDUAPP": ""
    },
    {
      "Number": 54,
      "Name": "农民",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "技艺（耕作），汽车驾驶（或运货马车），一项社交技能（取悦、话术、恐吓、说服），机械维修，自然，操作重型机械，追踪，任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 55,
      "Name": "联邦探员",
      "Credit": "20-40",
      "Profession_Point": "教育×4",
      "Skills": "汽车驾驶，格斗（斗殴），射击，法律，说服，潜行，侦查，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 56,
      "Name": "消防员",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，闪避，汽车驾驶，急救，跳跃，机械维修，操作重型机械，投掷。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 57,
      "Name": "驻外记者",
      "Credit": "10-40",
      "Profession_Point": "教育×4",
      "Skills": "历史，外语，母语，聆听，两项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 58,
      "Name": "法医",
      "Credit": "40-60",
      "Profession_Point": "教育×4",
      "Skills": "外语（拉丁文），图书馆，医学，说服，科学（生物学，药学，司法科学），侦查。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 59,
      "Name": "赌徒",
      "Credit": "8-50",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "会计，技艺（表演），两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，妙手，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 60,
      "Name": "黑帮-黑帮老大",
      "Credit": "60-95",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "格斗，射击，法律，聆听，两项社交技能（取悦、话术、恐吓、说服），心理学，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 61,
      "Name": "黑帮-马仔",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "汽车驾驶，格斗，射击，两项社交技能（取悦、话术、恐吓、说服），心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 62,
      "Name": "绅士、淑女",
      "Credit": "40-90",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（任一），两项社交技能（取悦、话术、恐吓、说服），射击（步枪/霰弹枪），历史，外语（任一），导航，骑乘。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 63,
      "Name": "游民",
      "Credit": "0-5",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "技艺（任一），攀爬，跳跃，聆听，锁匠或妙手，导航，潜行，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 64,
      "Name": "勤杂护工",
      "Credit": "6-15",
      "Profession_Point": "教育×2＋力量×2",
      "Skills": "电气维修，一项社交技能（取悦、话术、恐吓、说服），格斗（斗殴），急救，聆听，机械维修，心理学，潜行。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": 2,
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 65,
      "Name": "记者(原作向)-调查记者",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "技艺（艺术或摄影），一项社交技能（取悦、话术、恐吓、说服），历史，图书馆，母语，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 66,
      "Name": "记者(原作向)-通讯记者",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "技艺（表演），历史，聆听，母语，一项社交技能（取悦、话术、恐吓、说服），心理学，潜行，侦查。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 67,
      "Name": "法官",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "历史，恐吓，法律，图书馆，聆听，母语，说服，心理学。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 68,
      "Name": "实验室助理",
      "Credit": "10-30",
      "Profession_Point": "教育×4",
      "Skills": "计算机或图书馆，电气维修，外语，科学（化学和任意两项），侦查，任意一项其他个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 69,
      "Name": "工人-非熟练工人",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "汽车驾驶，电气维修，格斗，急救，机械维修，操作重型机械，投掷，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 70,
      "Name": "工人-伐木工",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，闪避，格斗（链锯），急救，跳跃，机械维修，自然或科学（生物学或植物学），投掷。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 71,
      "Name": "工人-矿工",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，科学（地质），跳跃，机械维修，操作重型机械，潜行，侦查，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 72,
      "Name": "律师",
      "Credit": "30-80",
      "Profession_Point": "教育×4",
      "Skills": "会计，法律，图书馆，两项社交技能（取悦、话术、恐吓、说服），心理学，两项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 73,
      "Name": "图书馆管理员（原作向）",
      "Credit": "9-35",
      "Profession_Point": "教育×4",
      "Skills": "会计，图书馆，外语，母语，任意四项其他个人特长或专业书籍主题。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 74,
      "Name": "技师",
      "Credit": "9-40",
      "Profession_Point": "教育×4",
      "Skills": "技艺（木工、焊接、管道工等），攀爬，汽车驾驶，电气维修，机械维修，操作重型机械，任意两项其他个人或时代或技术特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 75,
      "Name": "军官",
      "Credit": "20-70",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "会计，射击，导航，急救，两项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 76,
      "Name": "传教士",
      "Credit": "0-30",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（任一），急救，机械维修，医学，自然，一项社交技能（取悦、话术、恐吓、说服），任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 77,
      "Name": "登山家",
      "Credit": "30-60",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，急救，跳跃，聆听，导航，外语，生存（阿尔卑斯或类似），追踪。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 78,
      "Name": "博物馆管理员",
      "Credit": "10-30",
      "Profession_Point": "教育×4",
      "Skills": "会计，估价，考古，历史，图书馆，神秘学，外语，侦查。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 79,
      "Name": "音乐家",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋意志或敏捷×2",
      "Skills": "技艺（乐器），一项社交技能（取悦、话术、恐吓、说服），聆听，心理学，四项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": 2,
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 80,
      "Name": "护士",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "急救，聆听，医学，一项社交技能（取悦、话术、恐吓、说服），心理学，科学（生物学，化学），侦查。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 81,
      "Name": "神秘学家",
      "Credit": "9-65",
      "Profession_Point": "教育×4",
      "Skills": "人类学，历史，图书馆，一项社交技能（取悦、话术、恐吓、说服），神秘学，外语，科学（天文），任意一项其他个人或时代特长 ※经KP允许 可以包含克苏鲁神话",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 82,
      "Name": "旅行家",
      "Credit": "5-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "射击，急救，聆听，自然，导航，侦查，生存（任一），追踪。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 83,
      "Name": "超心理学家",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "人类学，技艺（摄影），历史，图书馆，神秘学，外语，心理学，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 84,
      "Name": "药剂师",
      "Credit": "35-75",
      "Profession_Point": "教育×4",
      "Skills": "会计，急救，外语（拉丁文），图书馆，一项社交技能（取悦、话术、恐吓、说服），心理学，科学（制药，化学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 85,
      "Name": "摄影师-摄影师",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "技艺（摄影），一项社交技能（取悦、话术、恐吓、说服），心理学，科学（化学），潜行，侦查，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 86,
      "Name": "摄影师-摄影记者",
      "Credit": "10-30",
      "Profession_Point": "教育×4",
      "Skills": "技艺（摄影），攀爬，一项社交技能（取悦、话术、恐吓、说服），外语，心理学，科学（化学），任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 87,
      "Name": "飞行员-飞行员",
      "Credit": "20-70",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "电气维修，机械维修，导航，操作重型机械，驾驶（飞行器），科学（天文），任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 88,
      "Name": "飞行员-特技飞行员（古典）",
      "Credit": "30-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，电气维修，聆听，机械维修，导航，驾驶（飞行器），侦查，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 89,
      "Name": "警方(原作向)-警探",
      "Credit": "20-50",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "技艺（表演）或乔装，射击，法律，聆听，一项社交技能（取悦、话术、恐吓、说服），心理学，侦查，一项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 90,
      "Name": "警方(原作向)-巡警",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "格斗（斗殴），射击，急救，一项社交技能（取悦、话术、恐吓、说服），法律，心理学，侦查和下面的一种个人特长：汽车驾驶或骑乘。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 91,
      "Name": "私家侦探",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "技艺（摄影），乔装，法律，图书馆，一项社交技能（取悦、话术、恐吓、说服），心理学，侦查，一项其他个人或时代特长（如计算机、锁匠、格斗、射击）。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 92,
      "Name": "教授（原作向）",
      "Credit": "20-70",
      "Profession_Point": "教育×4",
      "Skills": "图书馆，外语，母语，心理学，任意四项其他学术、时代或个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 93,
      "Name": "淘金客",
      "Credit": "0-10",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬、急救、历史、机械维修、导航、科学（地质），侦查，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 94,
      "Name": "性工作者",
      "Credit": "5-50",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（任一），两项社交技能（取悦、话术、恐吓、说服），闪避，心理学，妙手，潜行，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 95,
      "Name": "精神病学家",
      "Credit": "30-80",
      "Profession_Point": "教育×4",
      "Skills": "外语，聆听，医学，说服，精神分析，心理学，科学（生物学，化学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 96,
      "Name": "心理学家、精神分析学家",
      "Credit": "10-40",
      "Profession_Point": "教育×4",
      "Skills": "会计，图书馆，聆听，说服，精神分析，心理学，任意两项其他学术、个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 97,
      "Name": "研究员",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "历史，图书馆，一项社交技能（取悦、话术、恐吓、说服），外语，侦查，任意三项其他学术领域。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 98,
      "Name": "海员-军舰海员",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "电工或机械维修，格斗，射击，急救，导航，驾驶（船），生存（海上），游泳。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 99,
      "Name": "海员-民船海员",
      "Credit": "20-40",
      "Profession_Point": "教育×4",
      "Skills": "急救，机械维修，自然，导航，一项社交技能（取悦、话术、恐吓、说服），驾驶（船），侦查，游泳。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 100,
      "Name": "推销员",
      "Credit": "9-40",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），汽车驾驶，聆听，心理学，潜行或妙手，一项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 101,
      "Name": "科学家",
      "Credit": "9-50",
      "Profession_Point": "教育×4",
      "Skills": "任意三项科学专业领域，计算机或图书馆，外语，母语，一项社交技能（取悦、话术、恐吓、说服），侦查。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 102,
      "Name": "秘书",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋敏捷或外貌×2",
      "Skills": "会计，技艺（打字或速记），两项社交技能（取悦、话术、恐吓、说服），母语，图书馆或计算机，心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 103,
      "Name": "店老板",
      "Credit": "20-40",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），电气维修，聆听，机械维修，心理学，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 104,
      "Name": "士兵、海军陆战队士兵",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬或游泳，闪避，格斗，射击，潜行，生存，下面任选两项：急救、机械维修、外语。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 105,
      "Name": "间谍",
      "Credit": "20-60",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "技艺（表演）或乔装，射击，聆听，外语，一项社交技能（取悦、话术、恐吓、说服），心理学，妙手，潜行。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 106,
      "Name": "学生、实习生",
      "Credit": "5-10",
      "Profession_Point": "教育×4",
      "Skills": "语言（母语或外语），图书馆，聆听，三个学习的专业，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 107,
      "Name": "替身演员",
      "Credit": "10-50",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，闪避，电气维修或机械维修，格斗，急救，跳跃，游泳，下面任选一项：潜水、汽车驾驶、驾驶（任一），骑乘。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 108,
      "Name": "部落成员",
      "Credit": "0-15",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，格斗或投掷，聆听，自然，神秘学，侦查，游泳，生存（任一）。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 109,
      "Name": "殡葬师",
      "Credit": "20-40",
      "Profession_Point": "教育×4",
      "Skills": "会计，汽车驾驶，一项社交技能（取悦、话术、恐吓、说服），历史，神秘学，心理学，科学（生物学，化学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 110,
      "Name": "工会活动家",
      "Credit": "5-50",
      "Profession_Point": "教育×4",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），格斗（斗殴），法律，聆听，操作重型机械，心理学。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 111,
      "Name": "服务生",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "会计，技艺（任一），闪避，聆听，两项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 112,
      "Name": "白领工人-职员、主管",
      "Credit": "9-20",
      "Profession_Point": "教育×4",
      "Skills": "会计，语言，法律，图书馆或计算机，聆听，一项社交技能（取悦、话术、恐吓、说服），任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 113,
      "Name": "白领工人-中高层管理人员",
      "Credit": "20-80",
      "Profession_Point": "教育×4",
      "Skills": "会计，外语，法律，两项社交技能（取悦、话术、恐吓、说服），心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 114,
      "Name": "狂热者",
      "Credit": "0-30",
      "Profession_Point": "教育×2＋外貌或意志×2",
      "Skills": "历史，两项社交技能（取悦、话术、恐吓、说服），心理学，潜行，任意三项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": 2,
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 115,
      "Name": "饲养员",
      "Credit": "9-40",
      "Profession_Point": "教育×4",
      "Skills": "驯兽，会计，闪避，急救，自然，医学，科学（制药，动物学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 116,
      "Name": "大使",
      "Credit": "50-90",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "取悦，历史，恐吓，话术，聆听，母语，说服，心理学。(用一到两种外语取代前面两种技能)",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 117,
      "Name": "运动员（游泳/潜水）",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，跳跃，格斗（斗殴），外语，一项社交技能（取悦、话术、恐吓、说服），游泳，投掷，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 118,
      "Name": "运动员（高尔夫）",
      "Credit": "50-70",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，跳跃，格斗（斗殴），骑术，一项社交技能（取悦、话术、恐吓、说服），游泳，投掷，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 119,
      "Name": "运动员（网球）",
      "Credit": "30-70",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "跳跃，格斗（斗殴），闪避，一项社交技能（取悦、话术、恐吓、说服），心理学，侦察，投掷，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 120,
      "Name": "运动员（田径）",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬，跳跃，格斗（斗殴），外语，一项社交技能（取悦、话术、恐吓、说服），闪避，投掷，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 121,
      "Name": "发言人",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "乔装，闪避，三项社交技能（取悦、话术、恐吓、说服），心理学，外语，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 122,
      "Name": "保释担保人",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），法律，图书馆，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 123,
      "Name": "神职人员(天主教牧师)",
      "Credit": "20-70",
      "Profession_Point": "教育×4",
      "Skills": "会计，母语，外语(拉丁文)，图书馆，神秘学，一项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 124,
      "Name": "神职人员(新教牧师)",
      "Credit": "9-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，历史，图书馆，聆听，外语，一项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 125,
      "Name": "神职人员(犹太教拉比)",
      "Credit": "9-60",
      "Profession_Point": "教育×4",
      "Skills": "母语，外语（希伯来语），历史，图书馆，神秘学，一项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 126,
      "Name": "专栏作家",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "乔装，一项社交技能（取悦、话术、恐吓、说服），历史或图书馆，母语，外语，心理学，潜行。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 127,
      "Name": "社会主义者/激进主义者",
      "Credit": "0-30",
      "Profession_Point": "教育×2＋外貌或意志×2",
      "Skills": "格斗（斗殴），两项社交技能（取悦、话术、恐吓、说服），射击（手枪），外语，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": 2,
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 128,
      "Name": "撰稿人",
      "Credit": "20-60",
      "Profession_Point": "教育×4",
      "Skills": "母语，艺术（文学），两项社交技能（取悦、话术、恐吓、说服），历史，图书馆，聆听，心理学。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 129,
      "Name": "罪犯（赌博庄家）",
      "Credit": "50-80",
      "Profession_Point": "教育×2＋敏捷或外貌×2",
      "Skills": "会计,两项社交技能（取悦、话术、恐吓、说服）,心理学，侦察，妙手，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 130,
      "Name": "罪犯（放高利贷者）",
      "Credit": "50-80",
      "Profession_Point": "教育×2＋敏捷或外貌×2",
      "Skills": "会计，估价，两项社交技能（取悦、话术、恐吓、说服）,心理学，侦察，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 131,
      "Name": "罪犯（扒手）",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "乔装，一项社交技能（取悦、话术、恐吓、说服）,潜行，聆听，心理学，侦察，妙手，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 132,
      "Name": "罪犯（地下钱庄）",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "会计，法律，图书馆，聆听，说服，侦察，任意其他两项个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 133,
      "Name": "罪犯（黑律师）",
      "Credit": "30-80",
      "Profession_Point": "教育×4",
      "Skills": "会计，法律，图书馆，两项社交技能（取悦、话术、恐吓、说服），心理学，两项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 134,
      "Name": "牙医",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "急救、医学、外语（拉丁文）、心理学、科学（生物学，制药），任两种其他学术或个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 135,
      "Name": "外科医生/内科医生",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "急救、医学、外语（拉丁文）、心理学、科学（生物学，制药），任两种其他学术或个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 136,
      "Name": "整形医生",
      "Credit": "30-80",
      "Profession_Point": "教育×4",
      "Skills": "急救、医学、外语（拉丁文）、心理学、科学（生物学，制药），任两种其他学术或个人特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 137,
      "Name": "司机-公交司机",
      "Credit": "30-50",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "会计，汽车驾驶，电气维修，机械维修，导航，一项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 138,
      "Name": "实地调研员",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "会计，攀爬或跳跃，急救，图书馆，外语，一项社交技能（取悦、话术、恐吓、说服），两项研究领域相关技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 139,
      "Name": "电影摄制人员",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋意志或敏捷×2",
      "Skills": "艺术/工艺(任一,如摄影)，攀爬，汽车驾驶，电气维修，机械维修，一项社交技能（取悦、话术、恐吓、说服），任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": 2,
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 140,
      "Name": "司法科学家",
      "Credit": "30-50",
      "Profession_Point": "教育×4",
      "Skills": "艺术（摄影），医学，法律，科学（化学，司法科学，药学），侦察，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 141,
      "Name": "运动经理",
      "Credit": "20-70",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "会计，格斗（斗殴），闪避，两项社交技能（取悦、话术、恐吓、说服），急救，心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 142,
      "Name": "商船队船员",
      "Credit": "20-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "人类学，攀爬，电气维修或机械维修，跳跃，操作重型机械，外语，生存（海上），任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 143,
      "Name": "古典音乐家",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋意志或敏捷×2",
      "Skills": "会计，技艺（乐器），一项社交技能（取悦、话术、恐吓、说服），聆听，心理学，三项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": 2,
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 144,
      "Name": "赛车手/ 赛艇手",
      "Credit": "30-70",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "汽车驾驶，电气维修，机械维修，驾驶（船），心理学，侦察，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 145,
      "Name": "电台播音员",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "艺术（表演），母语，取悦，话术，说服，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 146,
      "Name": "推销员（圣经推销员）",
      "Credit": "9-40",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），汽车驾驶，聆听，心理学，潜行或妙手，一项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 147,
      "Name": "推销员（旅行推销员）",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），汽车驾驶，导航，聆听，心理学，一项其他技能。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 148,
      "Name": "小企业家",
      "Credit": "50-70",
      "Profession_Point": "教育×4",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），心理学，四项经营业务相关技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 149,
      "Name": "舞台工作人员",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "艺术/ 工艺（任一），母语，两项社交技能（取悦、话术、恐吓、说服），乔装，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 150,
      "Name": "证券经纪人",
      "Credit": "60-90",
      "Profession_Point": "教育×4",
      "Skills": "会计，估价，母语，两项社交技能（取悦、话术、恐吓、说服），心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 151,
      "Name": "勘测员",
      "Credit": "20-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，艺术（摄影），图书馆，博物学，导航，生存（任一），侦察，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 152,
      "Name": "电话接线员",
      "Credit": "20-50",
      "Profession_Point": "教育×4",
      "Skills": "母语，外语，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 153,
      "Name": "星探",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），法律，心理学，侦察，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 154,
      "Name": "医疗技术员",
      "Credit": "30-60",
      "Profession_Point": "教育×4",
      "Skills": "艺术（摄影），电气维修，图书馆，机械维修，医学，科学（生物，化学，药学）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 155,
      "Name": "队医",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "两项社交技能（取悦、话术、恐吓、说服），急救，医学，科学（药学），心理学，侦察，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 156,
      "Name": "寻宝猎人",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "估价，攀爬，汽车驾驶或驾驶（飞行器或船），电气维修或机械维修，历史，跳跃，一项社交技能（取悦、话术、恐吓、说服），侦察。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 157,
      "Name": "西部治安官",
      "Credit": "20-50",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "汽车驾驶，射击（任一），格斗（斗殴，鞭），法律，说服或心理学，骑术，追踪。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 158,
      "Name": "暴走族",
      "Credit": "5-10",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "格斗（斗殴），汽车驾驶，机械维修，话术，恐吓，任意三项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 159,
      "Name": "神职人员(和尚,尼姑)",
      "Credit": "5-60",
      "Profession_Point": "教育×4",
      "Skills": "艺术（书法），历史或图书馆，外语（汉语或梵语），学识（佛教），一项社交技能（取悦、话术、恐吓、说服），心理学，聆听，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 160,
      "Name": "神职人员(神官,巫女)",
      "Credit": "20-60",
      "Profession_Point": "教育×4",
      "Skills": "艺术（书法，另任一），图书馆，神秘学，学识（神道教），一项社交技能（取悦、话术、恐吓、说服），心理学，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 161,
      "Name": "风水师",
      "Credit": "20-50",
      "Profession_Point": "教育×4",
      "Skills": "艺术（任一），图书馆，神秘学，学识（道教），一项社交技能（取悦、话术、恐吓、说服），科学（天文，地质），任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 162,
      "Name": "家传降妖人",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "格斗（斗殴），博物学，神秘学，学识（佛教或神道教），心理学，潜行，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 163,
      "Name": "高中生(教育60以下)",
      "Credit": "5-10",
      "Profession_Point": "教育×4",
      "Skills": "攀爬、潜行、跳跃、图书馆、格斗（任一）、母语、科学（任一）或历史、外语（英语或其他）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 164,
      "Name": "市子（盲人）",
      "Credit": "5-30",
      "Profession_Point": "教育×4",
      "Skills": "艺术（表演），聆听，学识（神道教），神秘学，历史，话术或说服，心理学，任意一项特长。※经KP同意，可以用「灵媒」技能代替一项自选技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 165,
      "Name": "言灵师/阴阳师",
      "Credit": "9-20",
      "Profession_Point": "教育×4",
      "Skills": "艺术（书法，另任一），历史或图书馆，母语，学识（阴阳道），科学（天文），神秘学，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 166,
      "Name": "炼丹师",
      "Credit": "30-50",
      "Profession_Point": "教育×4",
      "Skills": "图书馆，医学，神秘学，科学（化学），博物学，学识（道教），外语（汉语），急救或精神分析。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 167,
      "Name": "外语教师",
      "Credit": "30-60",
      "Profession_Point": "教育×4",
      "Skills": "历史，聆听，母语，心理学，两项社交技能（取悦、话术、恐吓、说服），任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 168,
      "Name": "非法移民",
      "Credit": "0-5",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "乔装，话术，聆听，侦察，潜行，妙手，心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 169,
      "Name": "相扑力士(SIZ>80,STR>70)",
      "Credit": "9-60",
      "Profession_Point": "教育×2＋力量×2",
      "Skills": "闪避，格斗（斗殴），恐吓，跳跃，心理学，侦察，任意两项其他个人或时代特长。(你的体型可以超过99)",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": 2,
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 170,
      "Name": "渔民",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "机械维修，操作重型机械，游泳，驾驶（船），科学（天文），导航，博物学，侦察。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 171,
      "Name": "心理治疗师",
      "Credit": "30-50",
      "Profession_Point": "教育×4",
      "Skills": "艺术（任一），两项社交技能（取悦、话术、恐吓、说服），法律，外语，心理学，精神分析，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 172,
      "Name": "女学生",
      "Credit": "5-10",
      "Profession_Point": "教育×4",
      "Skills": "一项社交技能（取悦、话术、恐吓、说服），自行车驾驶，急救，聆听，艺术/ 工艺（任一），图书馆，格斗（矛）或射击（弓术），外语（任一）。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 173,
      "Name": "寄居学生",
      "Credit": "5-10",
      "Profession_Point": "教育×4",
      "Skills": "急救，会计，手艺（木匠），说服，图书馆，外语（任一），任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 174,
      "Name": "动物辅助治疗师",
      "Credit": "30-50",
      "Profession_Point": "教育×2＋外貌或意志×2",
      "Skills": "聆听，心理学，精神分析，科学（动物学），跳跃，追踪，博物学，任意一项其他个人或时代特长。\n跳跃，追踪，博物学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": 2,
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 175,
      "Name": "急诊医生/救援队员",
      "Credit": "10-50",
      "Profession_Point": "教育×4",
      "Skills": "医学，急救，科学（化学），锁匠，机械维修，电气维修，攀爬，跳跃。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 176,
      "Name": "密医",
      "Credit": "10-70",
      "Profession_Point": "教育×4",
      "Skills": "医学，急救，会计，一项社交技能（取悦、话术、恐吓、说服），法律，科学（药学），外语，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 177,
      "Name": "科学搜查研究员",
      "Credit": "30-50",
      "Profession_Point": "教育×4",
      "Skills": "艺术（摄影），医学，法律，科学（化学，司法科学，药学），侦察，任意一项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 178,
      "Name": "山岳救援队员",
      "Credit": "10-50",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "急救，聆听，跳跃，追踪，攀爬，导航，生存（山地），外语。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 179,
      "Name": "舞者",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演类，如表演、演唱、喜剧等），乔装，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 180,
      "Name": "服装设计师",
      "Credit": "20-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，技艺（摄影），技艺（任一），计算机或图书馆，乔装，心理学，侦察，任意一项其他个人特长。※可以通过成功的「侦察」检定，从对方的服饰判定其地位和收入等。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 181,
      "Name": "海上自卫队员",
      "Credit": "9-30",
      "Profession_Point": "教育×4",
      "Skills": "电气维修或机械维修，格斗，射击，急救，导航，驾驶（船），生存（海上），游泳。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 182,
      "Name": "海警",
      "Credit": "20-40",
      "Profession_Point": "教育×4",
      "Skills": "急救，机械维修，博物学，导航，一项社交技能（取悦、话术、恐吓、说服），驾驶（船），侦察，游泳。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 183,
      "Name": "陆上自卫队员",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬或游泳，闪避，格斗，射击，潜行，生存，下面任选两项：急救、机械维修、外语。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 184,
      "Name": "私人军事公司成员",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬或游泳，闪避，格斗，射击，潜行，生存，下面任选两项：急救、机械维修、外语。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 185,
      "Name": "冒险家教授",
      "Credit": "55-80",
      "Profession_Point": "教育×2＋外貌或敏捷或力量×2",
      "Skills": "攀爬或游泳，射击，历史，跳跃，博物学，导航，外语，生存。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 186,
      "Name": "评论家",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "乔装，一项社交技能（取悦、话术、恐吓、说服），历史或图书馆，母语，外语，心理学，潜行。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 187,
      "Name": "偶像",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演,歌唱,舞蹈），乔装，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 188,
      "Name": "歌手",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（歌唱,舞蹈,乐器），乔装，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 189,
      "Name": "搞笑艺人",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演,杂技,喜剧），乔装，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 190,
      "Name": "运动员艺人",
      "Credit": "9-20",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "攀爬，闪避，跳跃，投掷，侦察，游泳，任意两项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 191,
      "Name": "播音员",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "艺术（表演），母语，取悦，话术，说服，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 192,
      "Name": "主持人",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "艺术（表演），母语，取悦，话术，说服，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 193,
      "Name": "电视解说员",
      "Credit": "50-80",
      "Profession_Point": "教育×4",
      "Skills": "艺术（表演），母语，取悦，话术，说服，心理学，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 194,
      "Name": "网络明星",
      "Credit": "9-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "技艺（表演，歌唱，喜剧），乔装，两项社交技能（取悦、话术、恐吓、说服），聆听，心理学，计算机，电气维修。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 195,
      "Name": "经纪人",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "汽车驾驶、两项社交技能（取悦、话术、恐吓、说服），潜行，聆听，法律，任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 196,
      "Name": "捉鬼人",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "神秘学，科学（物理，化学，生物），机械维修，艺术（摄影），电气维修，一项社交技能（取悦、话术、恐吓、说服）。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 197,
      "Name": "占卜师、灵媒师",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋教育或外貌×2",
      "Skills": "艺术（表演），历史，图书馆，两项社交技能（取悦、话术、恐吓、说服），神秘学，心理学，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": 2
    },
    {
      "Number": 198,
      "Name": "机械师",
      "Credit": "9-40",
      "Profession_Point": "教育×4",
      "Skills": "技艺（木工、焊接、管道工等），攀爬，汽车驾驶，电气维修，机械维修，操作重型机械，任意两项其他个人或时代或技术特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 199,
      "Name": "厨师",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "手艺（烹饪），科学（生物，化学），格斗（斗殴），博物学，侦察，外语，任意一项其他个人或时代特长。",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 200,
      "Name": "网络犯罪者",
      "Credit": "10-70",
      "Profession_Point": "教育×4",
      "Skills": "计算机，电气维修，电子学，图书馆，侦察，一项社交技能（取悦、话术、恐吓、说服），任意两项其他技能。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 201,
      "Name": "佣兵",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "攀爬或游泳，闪避，格斗，射击，潜行，生存，下面任选两项：急救、机械维修、外语。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 202,
      "Name": "自宅警备员",
      "Credit": "1-10",
      "Profession_Point": "教育×4",
      "Skills": "计算机，聆听，潜行，图书馆，母语，任意三项符合尼特族形象的特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 203,
      "Name": "壮汉保镖",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "格斗（斗殴），射击，急救，一项社交技能（取悦、话术、恐吓、说服），法律，心理学，侦察和下面的一种个人特长：汽车驾驶或骑术。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 204,
      "Name": "游戏测试员",
      "Credit": "9-20",
      "Profession_Point": "教育×4",
      "Skills": "手艺（游戏），计算机，电气维修，电子学，聆听，一项社交技能（取悦、话术、恐吓、说服），任意两项其他个人或时代特长。",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 205,
      "Name": "交际花",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "艺术（任意），估价，潜行，一项社交技能（取悦、话术、恐吓、说服），急救，其他语言（欧洲），心理学，骑术，（乔装、钳工）中的一种，任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 206,
      "Name": "考古学家",
      "Credit": "30-60",
      "Profession_Point": "教育×4",
      "Skills": "会计，艺术（任意），估价，历史，图书馆，其他语言（欧洲），一项社交技能（取悦、话术、恐吓、说服），心理学，侦查，任意两项其他个人或时代特长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 207,
      "Name": "贵族",
      "Credit": "70-99",
      "Profession_Point": "教育×2＋教育或外貌×2",
      "Skills": "拉丁语，法律，其他语言（欧洲），一项社交技能（取悦、话术、恐吓、说服），骑术，射击（霰弹枪），任意三项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": 2
    },
    {
      "Number": 208,
      "Name": "艺术家",
      "Credit": "10-40",
      "Profession_Point": "教育×2＋敏捷或意志×2",
      "Skills": "艺术及手艺（任意多种），估价，历史，图书馆，其他语言（欧洲），侦查，任意两项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": 2,
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 209,
      "Name": "作家",
      "Credit": "10-40",
      "Profession_Point": "教育×4",
      "Skills": "艺术（写作），历史，图书馆，其他语言（欧洲），母语，一项社交技能（取悦、话术、恐吓、说服），心理学，任意两项其他个人或时代特长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 210,
      "Name": "马车夫",
      "Credit": "3-10",
      "Profession_Point": "教育×2＋敏捷×2",
      "Skills": "闪避，马车驾驶，跳跃，聆听，机械维修，博物学，导航，一项社交技能（取悦、话术、恐吓、说服），侦查，格斗（鞭），任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": 2,
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 211,
      "Name": "牧师",
      "Credit": "20-65",
      "Profession_Point": "教育×2＋外貌或意志×2",
      "Skills": "历史，拉丁语，图书馆，一项社交技能（取悦、话术、恐吓、说服），心理学，任意两项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": 2,
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 212,
      "Name": "咨询侦探",
      "Credit": "10-60",
      "Profession_Point": "教育×4",
      "Skills": "人类学，估价，科学（化学），急救，历史，法律，图书馆，聆听，心理学，其他语言（任意），侦查，追踪，任意两项其他个人或时代特长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 213,
      "Name": "工匠",
      "Credit": "9-35",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "会计，估价，手艺（任意多种），机械维修，一项社交技能（取悦、话术、恐吓、说服），侦查，任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 214,
      "Name": "罪犯",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋外貌或敏捷或力量×2",
      "Skills": "估价，乔装，一项社交技能（取悦、话术、恐吓、说服），潜行，锁匠，格斗（任意两项），任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 215,
      "Name": "业余艺术爱好者",
      "Credit": "10-70",
      "Profession_Point": "教育×2＋外貌×2",
      "Skills": "任意六项个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": 2,
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 216,
      "Name": "艺人",
      "Credit": "10-40",
      "Profession_Point": "教育×2＋外貌或意志×2",
      "Skills": "艺术（任意多种），乔装，闪避，两项社交技能（取悦、话术、恐吓、说服），聆听，母语，心理学，任意三项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": 2,
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 217,
      "Name": "退役军官",
      "Credit": "40-75",
      "Profession_Point": "教育×4",
      "Skills": "潜行，急救，射击（手枪、来复枪）,导航，其他语言（任意）,一项社交技能（取悦、话术、恐吓、说服）,心理学，骑术,格斗（剑），侦查，（攀爬、游泳）中的一种",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 218,
      "Name": "探险家",
      "Credit": "45-70",
      "Profession_Point": "教育×2＋外貌或敏捷或力量×2",
      "Skills": "人类学，考古学，估价，科学（生物学），攀爬，急救，射击（手枪、来复枪），格斗（斗殴），博物学，导航，其他语言（任意），驾驶（小艇，船，热气球），骑术，潜行，侦查，游泳，追踪",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 219,
      "Name": "私家侦探",
      "Credit": "9-40",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "会计，两项社交技能（取悦、话术、恐吓、说服），法律，图书馆，聆听，锁匠，艺术及手艺（摄影），侦查，任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 220,
      "Name": "记者",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "估价，闪避，两项社交技能（取悦、话术、恐吓、说服），图书馆，聆听，其他语言（欧洲），母语，艺术及手艺（摄影），心理学，侦查。",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 221,
      "Name": "劳工",
      "Credit": "0-10",
      "Profession_Point": "教育×2＋力量×2",
      "Skills": "估价，一项社交技能（取悦、话术、恐吓、说服），闪避，急救，机械维修，重型机械操作，任意一项其他个人或时代特长，以及从以下任选两种：（攀爬，斗殴，手艺（任意），马车驾驶，驾驶：船）",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": 2,
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 222,
      "Name": "律师",
      "Credit": "20-80",
      "Profession_Point": "教育×4",
      "Skills": "会计，估价，两项社交技能（取悦、话术、恐吓、说服），历史，拉丁语，法律，图书馆，聆听，心理学，任意两项其他个人或时代特长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 223,
      "Name": "医生",
      "Credit": "30-70",
      "Profession_Point": "教育×4",
      "Skills": "科学（生物学、药剂学），急救，拉丁语，图书馆，医学，心理学，任意两项其他个人或时代特长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 224,
      "Name": "警察",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "格斗（斗殴），闪避，一项社交技能（取悦、话术、恐吓、说服），急救，射击（手枪），法律，聆听，心理学，潜行，侦查",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 225,
      "Name": "教授/学者",
      "Credit": "20-50",
      "Profession_Point": "教育×4",
      "Skills": "图书馆，其他语言（欧洲），一项社交技能（取悦、话术、恐吓、说服），心理学，至多六种额外的学识技巧作为个人专长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 226,
      "Name": "科学家",
      "Credit": "10-60",
      "Profession_Point": "教育×4",
      "Skills": "手艺（任意），历史，图书馆，机械维修，一项社交技能（取悦、话术、恐吓、说服），侦查，至多六种其他学识技巧作为个人专长",
      "EDU": 4,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 227,
      "Name": "佣人",
      "Credit": "0-10",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "手艺（任意），闪避，聆听，潜行，任意一项其他个人或时代特长，以及从以下中最多选取三个：（会计，估价，马车驾驶，礼仪，急救，其他语言（欧洲），说服）",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 228,
      "Name": "店主",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "会计，估价，手艺（任意），聆听，一项社交技能（取悦、话术、恐吓、说服），心理学，侦查，任意一项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 229,
      "Name": "士兵",
      "Credit": "9-30",
      "Profession_Point": "教育×2＋力量或敏捷×2",
      "Skills": "闪避，急救，潜行，聆听，机械维修，射击（来复枪），潜行，侦查，任意两项其他个人或时代特长",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": 2,
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": "",
      "DEXAPPSTR": "",
      "EDUAPP": ""
    },
    {
      "Number": 230,
      "Name": "密探",
      "Credit": "30-70",
      "Profession_Point": "教育×2＋外貌或敏捷×2",
      "Skills": "乔装，一项社交技能（取悦、话术、恐吓、说服），潜行，历史，图书馆，聆听，锁匠，导航，其他语言（欧洲），心理学，侦查，格斗（任意）",
      "EDU": 2,
      "DEX": "",
      "DEXSTR": "",
      "APP": "",
      "APPPOW": "",
      "DEXPOW": "",
      "STR": "",
      "DEXAPP": 2,
      "DEXAPPSTR": "",
      "EDUAPP": ""
    }
  ]